--- #YAML:1.0
name:                Math-Random-MT-Auto
version:             5.06
abstract:            Auto-seeded Mersenne Twister PRNGs
license:             unrestricted
generated_by:        ExtUtils::MakeMaker version 6.32_01
distribution_type:   module
requires:     
    Carp:                          0
    Config:                        0
    Data::Dumper:                  0
    Exception::Class:              1.22
    Fcntl:                         0
    Object::InsideOut:             2.06
    Scalar::Util:                  1.18
    strict:                        0
    Test::More:                    0
    warnings:                      0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
