--- #YAML:1.0
name:               Math-Random-MT-Auto
version:            6.15
abstract:           Auto-seeded Mersenne Twister PRNGs
author:
    - Jerry D. Hedden <jdhedden AT cpan DOT org>
license:            unrestricted
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:               0
    Config:             0
    Data::Dumper:       0
    Exception::Class:   1.22
    Fcntl:              0
    Object::InsideOut:  2.06
    Scalar::Util:       1.18
    strict:             0
    Test::More:         0
    warnings:           0
    XSLoader:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    LWP::UserAgent: 0
    Win32::API: 0
